### ISSUE TITLE
Use Application CC's Endorsement Policy for WriteExternalState call in Weaver SDK.

### ISSUE THREAD

**Issue by sanvenDev** [hyperledger-labs/weaver-dlt-interoperability#288]
Modify SDK `interopFlow` by setting endorsement peers/orgs based on App CC

**Comment by sanvenDev** [comment]
Basic Solution: Get Endorsing peers/orgs as argument to interopFlow, and use it to submit transaction.

**Comment by VRamakrishna** [comment]
Endorsement policy can either be looked up from the channel configuration or provided to the `interopFlow` function as input by the calling app.

**Comment by knarayan** [comment]
Issue:

- > Interop-cc is calling app-cc as part of data-sharing.
- > If interop-cc is installed on 6 peers, and app-cc is not there on all those peers.
- > Then on the peers on which app-cc is not present, the interop-cc calls (to the app-cc function) will fail.

**Comment by VRamakrishna** [comment]
> We set the same endorsement policy(EP) of app-cc with the interop-cc as well. Hence, an endorsing peer of interop-cc when calls the app-cc, the call won't fail since both CCs are present on that endorsing peer.

@knarayan We can't do this because the Weaver interop CC is supposed to serve multiple app CCs, not just one. The endorsement policy of the Weaver CC ought to be independent of the endorsement policies of any app CC. The Weaver CC's endorsement policy comes into play only when policies and certificates are committed, and that's a network administration function which should be guided by network trust/failure assumptions (e.g., 2/3 of all orgs endorse the transactions).

The only right way to fix this issue is to add peer selection logic in the Weaver Interop SDK and not by manipulating endorsement policies.

**Comment by VRamakrishna** [comment]
API extension to take list of endorsing orgs as parameter was made in https://github.com/hyperledger-labs/weaver-dlt-interoperability/pull/314.

**Comment by VRamakrishna** [comment]
Fixed in PR #344
