### ISSUE TITLE
Verification policy to be part of the cli explicitly

### ISSUE THREAD

**Issue by knarayan** [hyperledger-labs/weaver-dlt-interoperability#70]
The `data transfer` protocol currently assumes that the endorsement policy is just one Org. And that specific org's signature is requested as part of the protocol.
It's possible to have multiple Orgs on the other hand as part of the endorsement. In that case, the requesting network can specify explicitly the verification policy as which specific Org's endorsement. We can have this specified via an option to the CLI as `--verification-policy` option.

**Comment by VRamakrishna** [comment]
Verification policies consisting of a single organization is because our Fabric testnets start up by default with just one org. Even if we start them with multiple orgs, the verification policy should align with what was configured during chaincode installation time. There's no strong reason to give the user an option to specify this via the command line.
